### ISSUE TITLE
YPP operations support service

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/marketing#327]
## Context

Related issue:
- https://github.com/Joystream/marketing/issues/258

[YPP programme](https://www.notion.so/joystream/YPP-programme-d492c2eb88ff4ace955b5f2902ec21fb) entails rewards paid out to participating channels based on misc activities undertaken by channels. Payment mechanism is executed via the Channel Payout proposal, that needs to be approved by council, for the channels to be paid from the Content Working Group budget. Payment details (which channels to pay and how much) are contained in a payload file, of JSON format generated by the role, responsible for the YPP programme. This role will be hired to perform this role into Marketing Working Group (⚠️ tbc). 

The process of operational management of the programme requires manual work and bears risks of miscalculation, delayed payouts and errors due to the manually transferred data. In order to minimise the operational risks, a tool can be created. 

## Suggestion
Create a standalone service that would integrate with Joystream system landscape and collect, organise, calculate and display all required information to effectively facilitate the payments. 

## Scope
- [ ] Create a standalone Service that would fetch the data from relevant systems of Joystream Landscape (Atlas, QN, Autosync service db) and collect the information about the joystream channels performance in YPP programme (rewardable actions). 
- [ ] The service should automatically calculate the rewards qualified for by channels in a given time period (same as council period)
- [ ] Rewardable actions data need to fetched and entitled payouts need to be calculated with frequency at least once in 30 min. 
- [ ] Actions and qualified payouts need to be added to the publicly accessible database
- [ ] The actions and payment information need to be presented in a way that can be easily validated by the operator. E.g. broken down by channels and periods, links to YT channel and JS channel needs to be present,  promo videos links to YT channel so that operator can check validity. 
- [ ] The payout details JSON file should be possible to generate by the tool, based on the information stored in the payouts DB. The payout file should comply with the format acceptable by the CLI service converting it to the payload file, used in payout proposals. 
- [ ] Parameters used in the calculation of payouts (such as reward per activity, activities rewarded and multiplier tiers) must be configurable in the tool.

## Requirements to the Tool 

1. The standalone service (tool) would not require authorisation to any of the JS services, and access to the tool can be governed by DAO and/ or JSG team. 
2. This service should automatically collect all of the required details about individual actions and surface it in a way that can be checked by the human operator for compliance with the programme policy. 
3. The service should calculate the rewards and organise it in a way that can be surfaced for the programme participants (creators) in a way of public DB that can be viewed in the browser without authorisation, or / and displayed in the dashboard of Atlas YPP module. 
4. Data model in the tool DB should reflect the payment cycles cadence, connected to council periods and periods of regular budget allocation to the working group account, from where the payments are done. 
5. There is no requirement to fully automate the calculation. Admin of the tool would maintain the input "config" with the parameters used in calculating the rewards. E.g. Tiers ranges are defined in Atlas config. Tool would rely on internally defined parameters, that are mimicking the setting in Atlas but not automatically updated, if changed in Atlas. This may impose some risk, but this is rather low to be dealt with by means of additional integration for Atlas codebase. 
6. ⚠️ the tool has to also facilitate calculation of the manually uploaded files and not just synced from YT.

## Programme Details Related to the Service Design

Below the core elements of operational management of the programme are covered in separate points, that collectively should inform the design of the new service. 

### Tiers
1. There are three Tiers, assigned to the participating Joystream channels, based on the number of subscribers on the connected YTT channel. 
2.  Currently Tiers are defined as: 
Tier 1 range | 50-5k
Tier 2 range | 5k-50k
Tier 3 range | 50k+
3. Tiers Rewards Multipliers defined as: 
Tier 1 multiplier | 1
Tier 2 multiplier | 3
Tier 3 multiplier | 10

### Rewardable actions

1. New signups
5. Upload content to Joystream channel manually / Upload content via Auto-sync service
6. Upload promotional content, provided by JSG to their YT channel / Promote Gleev app or Joystream Platform in the form of integrated advertising organically in their own video content. 
7. Refer other channels which results in the participation. 

### Actions information is stored in different systems
1.  Status of participating channels is stored in the YPP backend. 
2. New sign ups are stored in the Auto-sync BE service (YT channel ID, creator email, Joystream channel, date signed up)
4. Count of auto-synced videos are reflected in the Auto-sync service Dynamo DB.
5. Manually uploaded videos information can be taken from the QN db. 
8. Promotional content will be added to Youtube ⚠️ we can ask Creators to add a specific hashtag, like #gleevypp and have auto-sync service enabled, so that this video ends up in the auto-sync service DB, and the description field can be searched for this hashtag and added for evaluation.  Promotional content embedded organically can be requested to be added with an additional timestamp hashtag for easier review using  a mask of smth like: #yppts:hhmmss
9. Referrals are recorded in the YPP backend service, in the referrer channel ID field. .
10. Number of subscribers per YT channel is stored in the auto-sync service DB and re-fetched every 30 min. 
11. Tiers multiplier and Tiers for a given number of followers is stored in the Atlas config. 

### Formulas to calculate the rewards

**New sign up reward** = `New Sign up` x `Sign up reward` x `Tier multiplier`
**Referral reward** = `Added as referred to other sign ups` x `Number of channels referred` x `Referral Reward` x `Tier Multiplier`
**New Content Reward** = (`Number of videos uploaded or synced from YT channel for particular council term`- `Number of videos filtered out by content team (flag iscurated on QN)`) x `New Content Reward Per Video` x `Tier Multiplier`
**Joystream Promo Reward** = `Number of videos synced from YT channel with JS promotional content` x `Reward Per Joystream Promo video` x `Tier Multiplier`

**Comment by dmtrjsg** [comment]
Superseded by 
- https://github.com/Joystream/youtube-synch/issues/126
